version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./humhub:/var/www/html"
    ports:
      - "8080:80"
    links:
      - db
  
  db:
    image: hypriot/rpi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: humhub
      MYSQL_DATABASE: humhub
